project:
  type: website
  output-dir: docs


website:
  title: ğŸ‘€
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.md
      - text: "ì½ì€ ì±…"
        file: books.md
      - text: "ì˜¤ë‹µë…¸íŠ¸"
        file: review.md
      - text: "í”„ë¡œì íŠ¸"
        file: project.md
      - text: "ë¸”ë¡œê·¸"
        file: blog/blog.md
      - about.md
    right: 
      - icon: github
        href: https://github.com/lazychoi/lazychoi.github.io/issues

  sidebar:
    - title: "ì½ì€ ì±…"
      style: "docked"
      background: light
      contents:
        - books.md
        - books/This_is_coding_test.md
        - books/tiny_python_project.md
        - books/pandas_in_action.md
        - books/numpy_for_ml_dl.md
        - books/introduction_to_ML_with_python.md
        - books/python_machine_learning.md
        # - section: "ì´ê²ƒì´ ì½”ë”© í…ŒìŠ¤íŠ¸ë‹¤"
        #   contents: 
        # - section: "21ê°€ì§€ ì‘ê³  ì¬ë¯¸ë‚œ íŒŒì´ì¬ í”„ë¡œì íŠ¸"
        #   contents: 
        # - section: "íŒë‹¤ìŠ¤ ì¸ ì•¡ì…˜"
        #   contents: 
    - title: "ì˜¤ë‹µë…¸íŠ¸"
      contents:
        - review.md
        - review/python.md
        - review/algorithm.md
        - review/pkm.md
        - review/de.md
        - review/eda.md
        # - section: "íŒŒì´ì¬"
        #   contents: 
        # - section: "ì•Œê³ ë¦¬ì¦˜"
        #   contents:
        # - section: "ì§€ì‹ê´€ë¦¬"
        #   contents:
        # - section: "ê°œë°œí™˜ê²½"
        #   contents:
        # - section: "EDA"
        #   contents:


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    # number-sections: true
    # code-fold: true

lang: kr