project:
  type: website
  output-dir: docs
  # render:              # ìš”ê±°ë¥¼ ì¶”ê°€í•˜ë©´ ë©”ë‰´ê°€ ëœ¨ì§€ ì•ŠëŠ”ë‹¤.
  #   - "!notebooks/"

website:
  title: ğŸ‘€
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.md
      - text: "ì½ì€ ì±…"
        file: books.md
      - text: "ì˜¤ë‹µë…¸íŠ¸"
        file: review.md
      - text: "í”„ë¡œì íŠ¸"
        file: project.md
      - text: "ë¸”ë¡œê·¸"
        file: blog/index.md
      - about.md
    right: 
      - icon: github
        href: https://github.com/lazychoi/lazychoi.github.io/issues

  sidebar:
    - title: "ì½ì€ ì±…"
      style: "docked"
      background: light
      contents:
        - books.md
        - books/This_is_coding_test.md
        - books/tiny_python_project.md
        - books/pandas_in_action.md
        - books/numpy_for_ml_dl.md
        # - section: "ì´ê²ƒì´ ì½”ë”© í…ŒìŠ¤íŠ¸ë‹¤"
        #   contents: 
        # - section: "21ê°€ì§€ ì‘ê³  ì¬ë¯¸ë‚œ íŒŒì´ì¬ í”„ë¡œì íŠ¸"
        #   contents: 
        # - section: "íŒë‹¤ìŠ¤ ì¸ ì•¡ì…˜"
        #   contents: 
    - title: "ì˜¤ë‹µë…¸íŠ¸"
      contents:
        - review.md
        - section: "íŒŒì´ì¬"
          contents: 
            - review/python.md
        - section: "ì•Œê³ ë¦¬ì¦˜"
          contents:
            - review/algorithm.md
        - section: "ì§€ì‹ê´€ë¦¬"
          contents:
            - review/pkm.md
        - section: "ê°œë°œí™˜ê²½"
          contents:
            - review/de.md
        - section: "ì‹œê°í™”"
          contents:
            - review/visualization.md


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    # number-sections: true
    # code-fold: true

lang: kr