project:
  type: website
  output-dir: docs

website:
  title: ğŸ‘€
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.md
      - text: "ì½ì€ ì±…"
        file: books.md
      - text: "ì§€ì‹ê´€ë¦¬"
        file: pkm.md
      - text: "ê°œë°œí™˜ê²½"
        file: de.md
      - text: "ì˜¤ë‹µë…¸íŠ¸"
        file: review.md
      - text: "ì‹œê°í™”"
        file: visualization.md
      - text: "ë¸”ë¡œê·¸"
        file: blog/index.md
      - about.md
    right: 
      - icon: github
        href: https://github.com/lazychoi/lazychoi.github.io/issues

  sidebar:
    - title: "ì½ì€ ì±…"
      style: "docked"
      background: light
      contents:
        - books.md
        - section: "ì´ê²ƒì´ ì½”ë”© í…ŒìŠ¤íŠ¸ë‹¤"
          contents: 
            - books/This_is_coding_test.md
        - section: "21ê°€ì§€ ì‘ê³  ì¬ë¯¸ë‚œ íŒŒì´ì¬ í”„ë¡œì íŠ¸"
          contents: 
            - books/tiny_python_project.md
        - section: "íŒë‹¤ìŠ¤ ì¸ ì•¡ì…˜"
          contents: 
            - books/pandas_in_action.md

    - title: "ì§€ì‹ê´€ë¦¬"
      contents:
        - pkm.md
        # navigation items

    - title: "ê°œë°œí™˜ê²½"
      contents:
        - de.md
        # navigation items

    - title: "ì˜¤ë‹µë…¸íŠ¸"
      contents:
        - review.md
        - section: "íŒŒì´ì¬"
          contents: 
            - review/python.md
        - section: "ì•Œê³ ë¦¬ì¦˜"
          contents:
            - review/algorithm.md
    
    - title: "ì‹œê°í™”"
      contents:
        - visualization.md



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    # number-sections: true
    # code-fold: true

lang: kr