project:
  type: website
  output-dir: docs

execute: 
  freeze: auto

website:
  title: ğŸ‘€
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.md
      - text: "ì½ì€ ì±…"
        file: books.md
      - text: "ì˜¤ë‹µë…¸íŠ¸"
        file: review.md
      - text: "í”„ë¡œì íŠ¸"
        file: project.md
      - text: "ë¸”ë¡œê·¸"
        file: blog/blog.md
      - about.md
    right: 
      - icon: github
        href: https://github.com/lazychoi/lazychoi.github.io/issues

  sidebar:
    - title: "ì½ì€ ì±…"
      style: "docked"
      background: light
      contents:
        - books.md
        - books/cs_os.md
        - books/dom_enlightenment.md
        - books/This_is_coding_test.md
        - books/tiny_python_project.md
        - books/pandas_in_action.md
        - books/numpy_for_ml_dl.md
        - books/python_machine_learning.md
        - books/python_design_pattern.md
        # - section: "ì´ê²ƒì´ ì½”ë”© í…ŒìŠ¤íŠ¸ë‹¤"
        #   contents: 
        # - section: "21ê°€ì§€ ì‘ê³  ì¬ë¯¸ë‚œ íŒŒì´ì¬ í”„ë¡œì íŠ¸"
        #   contents: 
        # - section: "íŒë‹¤ìŠ¤ ì¸ ì•¡ì…˜"
        #   contents: 
    - title: "ì˜¤ë‹µë…¸íŠ¸"
      collapse-level: 1
      contents:
        - review.md
        - review/python.md
        - review/algorithm.md
        - review/javaSwing.md
        - review/pkm.md
        - review/de.md
        - review/eda.md
        - section: "ë¨¸ì‹  ëŸ¬ë‹"
          contents: 
              # - review/machine_learning.md
              - review/machine_learning/01_numpy.md
              - review/machine_learning/02_data_load.md
              - review/machine_learning/03_data_wrangling.md
              - review/machine_learning/04_numeric_data.md
              - review/machine_learning/05_categorical_data.md
              - review/machine_learning/06_text_data.md
              - review/machine_learning/07_datetime.md
              - review/machine_learning/08_image_data.md
              - review/machine_learning/09_feature_extraction.md
              - review/machine_learning/10_feature_selection.md
              - review/machine_learning/11_metrics.md
              - review/machine_learning/12_model_selection.md
              - review/machine_learning/13_linear_regression.md
        - review/deep_learning.md
        # - section: "ì•Œê³ ë¦¬ì¦˜"
        #   contents:
        # - section: "ì§€ì‹ê´€ë¦¬"
        #   contents:
        # - section: "ê°œë°œí™˜ê²½"
        #   contents:
        # - section: "EDA"
        #   contents:
  


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    # number-sections: true
    # code-fold: true

lang: kr